module.exports = {
    '.btn': '<div class="btn btn-primary">Button</div>',
    '.btn-xs': '<div class="btn btn-primary btn-xs">Extra small</div>',
    '.btn-sm': '<div class="btn btn-primary btn-sm">Small</div>',
    '.btn-lg': '<div class="btn btn-primary btn-lg">Large</div>',
    '.btn-default': '<div class="btn btn-default">Default</div>',
    '.btn-primary': '<div class="btn btn-primary">Primary</div>',
    '.btn-success': '<div class="btn btn-success">Success</div>',
    '.btn-info': '<div class="btn btn-info">Info</div>',
    '.btn-warning': '<div class="btn btn-warning">Warning</div>',
    '.btn-danger': '<div class="btn btn-danger">Danger</div>',
    '.btn-link': '<div class="btn btn-link">Link</div>',
    '.btn-block': '<div class="btn btn-primary btn-block">Block</div>',
    '.btn-group': '<div class="btn-group" role="group"><button type="button" class="btn btn-default">Left</button>' +
        '<button type="button" class="btn btn-default">Middle</button>' +
        '<button type="button" class="btn btn-default">Right</button></div>',
    'a': '<a href="#">Anchor</a>',
    '.nav': '<ul class="nav nav-pills"><li role="presentation" class="active"><a href="#">Home</a></li>' +
        '<li role="presentation"><a href="#">Profile</a></li><li role="presentation">' +
        '<a href="#">Messages</a></li></ul>',
    '.navbar': 'asdf',
    '.navbar-nav': 'asdf',
    '.navbar-default': 'asdf',
    'em': '<em>Italicized text</em>',
    'small': '<small>Small text</sm>',
    'strong': '<strong>Bold text</strong>',
    'h1': '<h1>Heading</h1>',
    'h2': '<h2>Heading</h2>',
    'h3': '<h3>Heading</h3>',
    'h4': '<h4>Heading</h4>',
    'h5': '<h5>Heading</h5>',
    'h6': '<h6>Heading</h6>',
    'ol': 'asdf',
    'ul':' asdf',
    'p': 'asdf',
    '.text-muted': '<p class="text-muted">Muted text</p>',
    '.text-primary': '<p class="text-primary">Primary text</p>',
    '.text-success': '<p class="text-success">Success text</p>',
    '.text-info': '<p class="text-info">Info text</p>',
    '.text-warning': '<p class="text-warning">Warning text</p>',
    '.text-danger': '<p class="text-danger">Danger text</p>',
    '.text-left': '<p class="text-left">Left-aligned text</p>',
    '.text-center': '<p class="text-center">Center-aligned text</p>',
    '.text-right': '<p class="text-right">Right-aligned text</p>',
    '.text-justify': '<p class="text-justify">Justified text</p>'
};