module.exports = {
  'Buttons': [
    '.btn',
    '.btn-xs',
    '.btn-sm',
    '.btn-lg',
    '.btn-default',
    '.btn-primary',
    '.btn-success',
    '.btn-info',
    '.btn-warning',
    '.btn-danger',
    '.btn-link',
    '.btn-block',
    '.btn-group'
  ],
  'Structure and Navigation': [
    'a',
    '.nav',
    '.navbar',
    '.navbar-nav',
    '.navbar-default'
  ],
  'Typography': [
    'em',
    'small',
    'strong',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'ol',
    'ul',
    'p',
    '.text-muted',
    '.text-primary',
    '.text-success',
    '.text-info',
    '.text-warning',
    '.text-danger',
    '.text-left',
    '.text-center',
    '.text-right',
    '.text-justify'
  ],
};